---
title: "CFRG Review"
author: "Kiri Daust"
date: "07/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, include = TRUE, message = FALSE, warning = FALSE)
library(shiny)
library(ccissdev)
library(data.table)
library(pool)
library(RPostgreSQL)

pool <- dbPool(
drv = RPostgres::Postgres(),
dbname = Sys.getenv("BCGOV_DB"),
host = Sys.getenv("BCGOV_HOST"),
port = 5432,
user = Sys.getenv("BCGOV_USR"),
password = Sys.getenv("BCGOV_PWD")
)

gcm_weight <- data.table(gcm = c("ACCESS-ESM1-5", "BCC-CSM2-MR", "CanESM5", "CNRM-ESM2-1", "EC-Earth3", 
"GFDL-ESM4", "GISS-E2-1-G", "INM-CM5-0", "IPSL-CM6A-LR", "MIROC6", 
"MPI-ESM1-2-HR", "MRI-ESM2-0", "UKESM1-0-LL"),
                         weight = c(1,1,0,1,1,1,1,0,1,1,1,1,0))

rcp_weight <- data.table(rcp = c("ssp126","ssp245","ssp370","ssp585"), 
                         weight = c(0.8,1,0.8,0))

all_weight <- as.data.table(expand.grid(gcm = gcm_weight$gcm,rcp = rcp_weight$rcp))
all_weight[gcm_weight,wgcm := i.weight, on = "gcm"]
all_weight[rcp_weight,wrcp := i.weight, on = "rcp"]
all_weight[,weight := wgcm*wrcp]

##silv functions
standardblocks <- function(data, siteref, siteserie) {
  sc <- data[
    SiteRef %in% siteref & SS_NoSpace %in% siteserie,
    list(Region, ZoneSubzone, SS_NoSpace, ccissSuit,Improve,PrefAcc,Spp)
  ]
  ss <- stocking_standards[
    Region %in% sc$Region & ZoneSubzone %in% sc$ZoneSubzone & SS_NoSpace %in% sc$SS_NoSpace
  ]
  do.call(span, lapply(unique(ss$Standard), standardblock, ss = ss, sc = sc))
}

standardblock <- function(std, ss, sc) {
  ss <- ss[Standard %in% std]
  ss[, TextStyle := ""]
  sc[,TxtCciss := ""]
  
  # Some logic to flag specie with different Suitability than CCISS
  ss[sc, on = "Species==Spp", ProjFeas := suppressWarnings(as.integer(i.ccissSuit))]
  setnafill(ss, fill = 4L, cols = "ProjFeas")
  ss[Suitability > ProjFeas, TextStyle := "color:blue"]
  ss[Suitability < ProjFeas, TextStyle := "color:orange"]
  ss[ProjFeas == 4L, TextStyle := "color:red;text-decoration:line-through"]
  
  # cciss colouring
  sc[Improve > 67,TxtCciss := "color:green"]
  sc[Improve < 33, TxtCciss := "color:red"]
  
  si <- stocking_info[Standard == std]
  sh <- stocking_height[Standard == std]
  list(
    tags$small("Forest Region: ", tags$b(si$Region, .noWS = c("before", "after")), .noWS = "inside"),
    tags$table(width = "100%", style = "white-space: nowrap;",
               # Report formatting gray out the first row, so faking a row
               tags$tr(
                 tags$td(width = "50%", style = "vertical-align: top; padding:0; background-color:white; border:none",
                         tags$small(tags$b("Regeneration")),
                         tags$hr(style = "padding: 0; margin: 0 0 3px 0; height: 2px; background-color: darkgreen; border: 0px"),
                         tags$table(
                           width = "100%",
                           tags$tr(
                             tags$td(tags$b("Standards ID")),
                             tags$td(tags$b(paste(ss[!is.na(Standard), unique(Standard)], collapse = ", ")),style = "border-right: 2px solid;"),
                             tags$td(tags$b("Climate Change")),
                             tags$td(tags$b("CCISS Feasibility"))
                           ),
                           tags$tr(
                             tags$td("Primary"),
                             ss[!is.na(Species) & Suitability %in% 1L, sppnotes(Species, Footnotes, TextStyle)],
                             sc[!is.na(Spp) & ccissSuit %in% "1", sppnotes_cciss(Spp,TxtCciss)],
                             tags$td("High - E1")
                           ),
                           
                           tags$tr(
                             tags$td("Secondary"),
                             ss[!is.na(Species) & Suitability %in% 2L, sppnotes(Species, Footnotes, TextStyle)],
                             sc[!is.na(Spp) & ccissSuit %in% "2", sppnotes_cciss(Spp,TxtCciss)],
                             tags$td("Moderate - E2")
                           ),
                           
                           tags$tr(
                             tags$td("Tertiary"),
                             ss[!is.na(Species) & Suitability %in% 3L, sppnotes(Species, Footnotes, TextStyle)],
                             sc[!is.na(Spp) & ccissSuit %in% "3", sppnotes_cciss(Spp,TxtCciss)],
                             tags$td("Low - E1")
                           ),
                           
                           tags$tr(
                             tags$td("Broadleaf"),
                             ss[!is.na(Species) & Suitability %in% 0L, sppnotes(Species, Footnotes, TextStyle)],
                             sc[!is.na(Spp) & ccissSuit %in% "10", sppnotes_cciss(Spp,TxtCciss)],
                             tags$td("Trial"),
                             style = "border-bottom:1px solid black;"
                           ),
                           tags$tr(
                             tags$td("Preferred (p)"),
                             ss[!is.na(Species) & PreferredAcceptable %in% "P", sppnotes(Species, Footnotes, TextStyle)],
                             sc[!is.na(Spp) & PrefAcc %in% "P", sppnotes_cciss(Spp,TxtCciss)],
                             tags$td("")
                           ),
                           tags$tr(
                             tags$td("Acceptable (a)"),
                             ss[!is.na(Species) & PreferredAcceptable %in% "A", sppnotes(Species, Footnotes, TextStyle)],
                             sc[!is.na(Spp) & PrefAcc %in% "A", sppnotes_cciss(Spp,TxtCciss)],
                             tags$td("")
                           )
                         )
                 ),
                 tags$td(width = "50%", style = "vertical-align: top; padding:0px 0px 0px 8px; background-color:white; border:none",
                         tags$small(tags$b("Stocking (i) - well spaced/ha")),
                         tags$hr(style = "padding: 0; margin: 0 0 3px 0; height: 2px; background-color: darkgreen; border: 0px"),
                         tags$table(
                           width = "100%",
                           tags$tr(
                             tags$td(tags$b("Target")),
                             tags$td(tags$b("Min pa")),
                             tags$td(tags$b("Min p")),
                             tags$td(tags$b("Regen Delay (max yrs)"))
                           ),
                           tags$tr(
                             tags$td(si$StockingTarget),
                             tags$td(si$StockingMINpa),
                             tags$td(si$StockingMINp),
                             tags$td(si$StockingDelay)
                           )
                         ),
                         tags$br(),
                         tags$small(tags$b("Free Growing Guide")),
                         tags$hr(style = "padding: 0; margin: 0 0 3px 0; height: 2px; background-color: #003366; border: 0px"),
                         tags$table(
                           width = "100%",
                           tags$tr(
                             tags$td(tags$b("Earliest (yrs)")),
                             tags$td(tags$b("Latest(yrs)")),
                             tags$td(tags$b("Min Height (m)")),
                             tags$td(tags$b("Min Height (m)"))
                           ),
                           tags$tr(
                             tags$td(si$AssessmentEarliest),
                             tags$td(si$AssessmentLatest),
                             tags$td(style = "white-space: normal;", sh[!Flag %in% TRUE, paste(Species, Height, sep = ": ", collapse = ", ")]),
                             tags$td(style = "white-space: normal;", sh[Flag %in% TRUE, paste(Species, Height, sep = ": ", collapse = ", ")])
                           )
                         )
                 )
               ),
               tags$tr(
                 tags$td(colspan = "2", style = "white-space:normal; vertical-align: top; padding:0; background-color:white; border:none",
                         tags$small(tags$b("Footnotes")),
                         tags$hr(style = "padding: 0; margin: 0 0 3px 0; height: 2px; background-color: #003366; border: 0px"),
                         {
                           fn <- ss[PreferredAcceptable %in% c("A", "P") | Suitability %in% 1:3, sort(as.integer(unique(unlist(Footnotes))))]
                           fnt <- footnotes[match(fn, `Revised Footnote`), `Revised Footnote Text`]
                           fnshiny <- mapply(function(footnote, text) {list(tags$sup(footnote), tags$small(text), tags$br())}, fn, fnt, SIMPLIFY = FALSE, USE.NAMES = FALSE)
                           do.call(span, fnshiny)
                         }
                 )
               )
    )
  )
}

# Function to format Species with footnotes
sppnotes <- function(spp, notes, textstyle) {
  ret <- vector("list", length(spp))
  for (i in seq_len(length(spp))) {
    fn <- paste0(sort(as.integer(unique(unlist(notes[i])))), collapse = ",")
    ret[[i]] <- tags$span(tags$span(style = textstyle[i], spp[i]),
                          tags$sup(fn, .noWS = htmltools:::noWSOptions),
                          if (i < length(spp)) {", "} else {""}, .noWS = htmltools:::noWSOptions)
  }
  ret[["style"]] <- "white-space:normal;"
  do.call(tags$td, ret)
}

sppnotes_cciss <- function(spp, textstyle) {
  ret <- vector("list", length(spp))
  for (i in seq_len(length(spp))) {
    ret[[i]] <- tags$span(tags$span(style = textstyle[i], spp[i]),
                          if (i < length(spp)) {", "} else {""}, .noWS = htmltools:::noWSOptions)
  }
  ret[["style"]] <- "white-space:normal; border-left: 2px solid;"
  do.call(tags$td, ret)
}



reg_cw <- fread("District_Region_Crosswalk.csv")
```

```{r index, results='asis'}
tags$h2("All BGC Units")
dist_select <- "BUL"
bgc_opts <- dbGetQuery(pool,paste0("select distinct bgc from preselected_points where dist_code = '",dist_select,"'"))[,1]
for(i in 1:length(bgc_opts)){
  bgc_select <- bgc_opts[i]
  temp <- dbGetQuery(pool,paste0("select count(*) from preselected_points where bgc = '",bgc_select,"' and dist_code = '",dist_select,"'"))[,1]
  if(temp[1] > 25){
    cat(sprintf("<a href=\"#Site_Unit:%s\">- Unit %s</a><br>", bgc_select,bgc_select))
  }
}
```

```{r,results='asis', out.height="auto"}
for(bgc_select in bgc_opts){
  cat("<P style='page-break-before: always'>")    #forced new-page happens here.
  pNums <- dbGetBGC(pool,bgc_select,dist_select,100)
  if(length(pNums) > 25){
    dat <- dbGetCCISS(pool,pNums,T,all_weight)
    eda <- edatopicOverlap(dat,E1,E1_Phase,onlyRegular = T)
    feas <- ccissOutput(eda,S1,R1,F1,c(0.3,0.35,0.35),c(0.3,0.3,0.3,0.1))
    feasSum <- feas$Summary
    feasSum[,Region := reg_cw[dist_code == dist_select,reg_cfrg]]
    feasSum[,ZoneSubzone := SiteRef]
    feasSum[
        stocking_standards, 
        `:=`(CFSuitability = as.character(i.Suitability),
        PrefAcc = i.PreferredAcceptable),
        on = c(Region = "Region", ZoneSubzone = "ZoneSubzone", SS_NoSpace = "SS_NoSpace", Spp = "Species")
      ]
    
    feasSum[cfrg_rules,PrefAcc_cciss := i.PrefAcc, on = c("Spp",ccissSuit = "Feasible")]
    feasSum[is.na(PrefAcc_cciss),PrefAcc_cciss := "X"]
    feasSum[,NoPref := if(any(PrefAcc_cciss == "P")) T else F, by = .(SS_NoSpace)]
    feasSum[NoPref == F & PrefAcc_cciss == "A", PrefAcc_cciss := "P"]
    feasSum[,NoPref := NULL]
    feasSum[is.na(PrefAcc), PrefAcc := "X"]
    feasSum[ccissSuit %in% c(1,2,3) & Curr == "X",ccissSuit := 10]
    
    siteseries <- unique(feasSum$SS_NoSpace)
    print(
      tagList(tags$hr(style = "padding: 0; margin: 0 0 3px 0; height: 2px; background-color: purple; border: 0px"),
              tags$h2(paste0("Site_Unit:",bgc_select)),
              tags$hr(style = "padding: 0; margin: 0 0 3px 0; height: 2px; background-color: purple; border: 0px"))
    )
    for(siteserie in siteseries){
        f1 <- feasSum[SS_NoSpace == siteserie,]
        s1 <- stocking_standards[
          Region %in% f1$Region & ZoneSubzone %in% f1$ZoneSubzone & SS_NoSpace %in% f1$SS_NoSpace
        ]
        if(nrow(s1) > 0){
          print(htmltools::tagList(
          tags$h3("Site Series: ", tags$b(siteserie, .noWS = c("before", "after"))),
          standardblocks(feasSum, bgc_select, siteserie),
        ))
        }
    }
  }
}

poolClose(pool)
```

```{=html}
<style type="text/css">
  h2 {font-weight:900 !important;}
  .main-content {max-width: none !important; padding:3rem 3rem !important}
  .table {width: auto !important;}
  .table td {vertical-align: top !important;}
  table.table-centered {margin-left:auto !important; margin-right:auto !important}
</style>
```

```{=html}
<script type="text/javascript">
  // When the document is fully rendered...
  $(document).ready(function() {
    // ...select all header elements...
    $('h1, h2, h3, h4, h5').each(function() {
      console.log($(this).html());
      $(this).attr('id', $(this).html());
    });
  });
</script>
```
