---
title: Climate Change Informed Species Selection (CCISS) Tool
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
editor_options: 
  markdown: 
    wrap: 72
---

Climate Change Informed Species Selection (CCISS – pronounced ‘kiss’) is a Biogeoclimatic Ecosystem Classification-based analysis framework built to anticipate the climate change implications to tree species environmental suitability at a site specific level. The CCISS tool is a web-based application that makes this analysis accessible to practitioners to help guide climate change adaptation in reforestation decisions.

Understanding climate- and site-level species suitability is one of the foundational pieces of information that practitioners require for the creation of silvicultural prescriptions that will lead to successful reforestation over a rotation period. Climate change will affect this goal by progressively altering environmental conditions and therefore the suitability of tree species established on a site over time.

To address this challenge, the CCISS tool projects changes to species environmental suitability at a site series level for any user selected location in the province and estimates the future suitability of a tree species to this changing climate. To account for future climate uncertainty, the tool looks at a wide range of global climate change models and emissions scenarios to capture the range of plausible climate futures for any location in BC in 20-year periods out to 2100.

To assist users, the tool compares the current species selection guidance in the Chief Forester's Reference Guide (CFRG) with the future forecast from the CCISS analysis. Reports from the tool highlight where currently acceptable species are stable/improving or declining/unsuitable and where new species have become suitable and could be considered as candidates for assisted migration.

The CCISS tool has been designed to assist professional decisions in the following contexts:

1. Selecting tree species for individual reforestation prescriptions
2. Designing stocking standards for reforestation policy
3. Setting landscape-level stocking standards to manage risk
4. Identifying best locations for off-site species reforestation trials and/or assisted range expansion
5. Identifying regions and site conditions where forests and tree species are at highest risk to climate change stresses
6. Learning about the distribution and ecological tolerances of BC's tree species

### Structure

The CCISS tool is organized into seven tabs.

1.	__SELECT SITES:__ User selects points or areas of interest using one of 3 methods
    i.	Single points
    ii.	By selected BGCs or BGCs within districts
    iii.	By submitted CSV file with user site locations
  
2.	__SUITABILITY REPORT:__ Reports on suitability projections, presented in detailed or summary form. 
    a.	__Detailed__: This generates a report showing the suitability projections for each species for a chosen site series at each point or area of interest
    b.	__Summary__: This generates a comparison of the Chief Forester's Reference Guide stocking standards and the CCISS projected suitability ratings
    
3.	__BEC FUTURES:__ The modeled ratio of projected biogeoclimatic (BGC) units, by time period, presented in two options.
    a.	__Chart__: A stacked bar chart that shows the ratio of BGC units being predicted from the selected global climate models (GCMs) and climate scenario models in each time period. Optionally, the site series that are equivalent within each BGC unit can be displayed.
    b.	__Map__: Show biogeoclimatic map of western North America with the target BGC unit highlighted and the source BGC units for a selected future time period shown in greyscale. 

4.	__SILVICS:__ This tab provides several tables of information based on Klinka et al. (2000)'s comparison of silvical characteristics.
    a.	__About__: Explanation of the information
    b.  __Tolerance__: Comparison of species tolerances
    c.	__Resistance__: Comparison of species resistance and potential risk comparisons
    d.  __Regeneration stage__: Comparison of regeneration stage characteristics
    e.  __Maturing stage__: Comparison of maturing stage characteristics

5.	__EXPORT__: Exporting reports or data for off-line use
    i. Produce report: Select report format (html or pdf)
    ii. Export data: Select data format (csv or rds)

6.	__CCISS SPATIAL__: Explore maps of CCISS results and graphical summaries of subregions
    i. Interactive maps of biogeoclimatic projections, climatic novelty, and tree species suitability changes
    ii. Graphical summaries and spatial data download for subregions (Forest Districts and Forest Landscape Planning Areas)

7.	__DOCUMENTATION__: Help files and data sources
    a.	__Overview__: 
    b.	__Instructions (How to CCISS)__: Instructions on how to use the tool
    c.	__Methods (How the tool works)__: Detailed background information about what's happening "under the hood"
    d.	__Known issues__: Documentation on current known issues with the tool
    e.  __Using CCISS for decisions__: Support and guidance for using CCISS as a decision-making tool
    f.  __Definitions__: Glossary of terms, BEC codes, species codes, etc.
    g.  __Providing feedback__: Ways users can report issues or provide suggestions for future improvements
    h.  __FAQs__: Frequently asked questions
    i.  __Model information__: Version of input data and models
    j.  __Shiny app information__: Github repo, license, and other info
   
### Acknowledgements

The CCISS team is: 

-	Will MacKenzie--—Lead Scientist
-	Kiri Daust--—Software development 
-	Vanessa Comeau--—Interpretations and engagement
-	Courtney Collins—--Ecological modeling
-	Destany Crane—--Open data standards
- Deb Obrist---Interpretations
-	Colin Mahony—--Team lead

The following BC Ministry of Forests ecologists provided regional environmental suitability ratings for tree species: Allen Banner (ret.), Ray Coupe (ret.), Del Meidinger (ret.), Tom Braumandl (ret.), Bob Green (ret.), Richard Kabzems (ret.), Bruce Rogers (dec.), Heather Klassen, Sari Saunders, Deb MacKillop, Hardy Griesbauer, Mike Ryan, Erica Lilles and Daniel Sklar. 

Pam Dykstra championed the CCISS project and its applications in ecosystem management and policy.

Shirley Mah and Kevin Astridge led early work on climate change informed species selection, including concept development and public consultation. 

Dr. Tongli Wang (University of British Columbia) and Dr. Andreas Hamann (University of Alberta) pioneered the core methods used in CCISS, namely biogeoclimatic projections and their translation into tree species suitability projection.

Finally, we acknowledge the World Climate Research Program’s Working Group on Coupled Modelling, which is responsible for the Coupled Model Intercomparison Project (CMIP6), and we thank the global climate climate modelling groups for producing and making available their model output.
    
### References: 

Chief Forester's Reference Guide: https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/silviculture/stocking-standards

Klinka, K., J. Worrall, L. Skoda, and P. Varga. 2000. The Distribution and Synopsis of 
Ecological and Silvical Characteristics of Tree Species of British Columbia's Forests. Canadian Cartographics Ltd., Coquitlam, B.C.

##### Additional Documents:
[Forest Ecology and Management Science Paper](./downloadable_docs/MacKenzieMahony2021_CCISS_FEM.pdf)

