---
title: 
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
editor_options: 
  markdown: 
    wrap: 72
---

## Tree species feasibility report

This is the main report of the CCISS tool. The Summary mode of this
report provides a comparison of the Chief Forester's Reference Guide for
Stocking Standards (CFRG) and the CCISS feasibility assessment. The
Detailed mode shows the distribution of feasibility ratings for the
global climate model ensemble in each time period.

The concept and definitions of CCISS feasibility ratings are discussed
in more detail <a href="3c_FeasibilityRatings.html">here</a>.

### Selection/Filter pane

In the left pane select the BGC subzone/variant and then the site series of
interest. The edatopic space of the selected site series is displayed in
the graphic below for reference. By default the report will show all
species that are predicted to be feasible in at least one model and time
period. Choose the "Feasible Only" option to limit the list to species
that meet the threshold for classification as feasible across the global
climate model ensemble in any of the time periods.

### Detailed report

This report shows modelled feasibility ratios for each species in the
selected site series for each time period. The colour legend for
feasibility ratings is on the left hand pane. The mapped biogeoclimatic
unit represents the historical equilibrium climate approximated by the
climatic conditions of the 1961-1990 period. The recent time period
(2001-2020) has two bars: one for the observed climate (measured by
weather stations), and one for the climates simulated by the ensemble of
global climate models. These two bars aren't necessarily expected to
agree: The modelled climates sample a large range of possible recent
conditions, of which the observed recent climate is only one.

The report then summarizes the baseline suitability ratings and
forecasted feasibility ratings for each species in the following order:

1.  The **CFRG suitability** rating: Suitability ratings taken directly
    from the Chief foresters reference guide

2.  The **CFRG P/A** value: Preferred/Acceptable ratings taken directly
    from the Chief foresters reference guide

3.  The **Historical Environmental Suitability**: Expert baseline
    environmental suitability rating for site series.

4.  **CCISS Establishment Feasibility**: The feasibility rating based on
    the baseline (1961-1990), recent observed (2001-2020), and 2021-2040
    future projected feasibilities. This indicates the likely level of
    constraints for successful establishment of the species in the
    present climate. Default model settings equally weight time periods.

5.  **CCISS Maturation Feasibility**: The mean feasibility rating across
    the 20-year normal periods (2021-2100). This indicates the inferred
    feasibility of successfully growing an established to maturity (80
    years). Default model settings equally weight time periods

6.  **P/A**: Assessed preferred/acceptable rating based on establishment
    and maturation feasibility.

7.  **Trend**: the proportion of the GCM simulations indicating
    improving/stable feasibility (numerator) vs. declining feasibility
    or remaining unfeasible.

The weights used to calculate Establishment Feasibility and Maturation
Feasibility can be modified using the "Adjust Parameters" dialog box in
the "Select Sites" tab.

#### Novel climates

Climatic novelty refers to the degree of mismatch between a future climate condition and the biogeoclimatic analog it is classified as. Valid inferences of species suitability are not possible in highly novel climates. By default, biogeoclimatic projections with high (5$\sigma$) novelty are removed from CCISS results and replaced with a black bar in the detailed feasibility results. Removal of novel climates can be disabled or adjusted using the "Adjust Parameters" dialog box in
the "Select Sites" tab. See Documentation - Methods - Novel Climates for more details.  

### Summary report

This report compares CCISS maturation feasibility with the Chief
Forester's Reference Guide for Stocking Standards. Species codes are
coloured according to trends in their future feasibility using the
legend at the bottom of the selection pane: improving (green),
decreasing (red). Species added to the CCISS stocking standard are
coloured purple, and species dropped from the CCISS stocking standard
are strike-through.
