---
title: 
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
editor_options: 
  markdown: 
    wrap: 72
---

### CCISS Rulesets

To account for uncertainty in future climates, CCISS uses a suite of 8
global climate models (GCMs) and 3 emissions scenarios (SSPs). This
strategy usually leads to multiple projected biogeoclimatic subzone/variants 
(BGC units) for each requested location (as shown in the "BGC Futures" tab) and 
thus, a range of projected suitabilities. While it is often informative to 
observe the full distribution of projected suitabilities, CCISS also uses 
rulesets to "summarise" the projected suitabilities into a single value.

#### CCISS Suitability

For each future period, the raw output of CCISS projections consists of
possible suitability values (E1-high suitability, E2-moderate
suitability, E3-low suitability, or X-not suitable) for each climate
model/emissions scenario combination, i.e. a "vote" for a given
suitability. (Note that due to overlapping edatopic space, there is
often not a one-to-one match between models and suitability values. See
the "Methods - Edatopic Overlap" tab for a detailed explanation of edatopic
overlap.) To summarise these votes into a single "projected suitability"
for each tree species at each requested location, we use the following
equation:

$$
\text{Projected Suitability} = P(E1) + 2P(E2) + 3P(E3) + 5P(X)
$$

where $P(s)$ represents the proportion of votes for suitability $s$ and
$P(E1) + P(E2) +P(E3) + P(X) = 1$. In essence, this is a weighted
average of the suitability values, with slightly higher weight on
non-suitable predictions. (Note that the E4 suitability class is not yet been incorporated into the CCISS model. For more information see "Methods - Suitability ratings") 

#### Establishment and Maturity

Using the projected suitability described above, CCISS then further
summarises these ratings over multiple time periods into an Establishment
Suitability and a Maturity Suitability. Both of these are calculated as
weighted averages of period-wise suitability: Establishment Suitability
uses 1961-1990 (historic environmental suitability), 2001-2020, and 2021-2040
projected suitabilities, while Maturity Suitability uses all future periods 
(2021 - 2100). The weighting of the different periods are adjustable in "Model
Parameters", and are by default almost equally weighted.

There is one exception to the Establishment Suitability values: if a
species is listed as historically unsuitable, but has a E1, E2 or E3
Maturity Suitability, it gets listed as a "Trial" in Establishment
Suitability.

#### Preferred/Acceptable

In order to align with the Chief Forester's Reference Guide, CCISS also
creates a projected Preferred/Acceptable rating, based on
species-specific suitability cutoffs and the Maturity Suitability
(described above). The CCISS tool uses these in the "Summary"
suitability view, as well as in the exported data. For most conifer
species, a suitability of E1 or E2 translates to $P$ (preferred), and a
suitability of E3 translates to $A$ (acceptable). There are a few
exceptions, such as **Hm** (mountain hemlock), which is only assigned
$P$ with a suitability of E1. With the exception of Oaks, most broadleaf
species are not assigned a $P/A$ value. This may be updated as additional information on broadleaf suitability becomes available. 