---
title: 
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
editor_options: 
  markdown: 
    wrap: 72
---

### CCISS Expert Review

#### As of April 2025

Given the complexity of forest ecosystems and climate change impacts on
tree species, it is essential that the CCISS tool undergoes evaluation
by experts. In 2024-25, the BC Ministry of Forest (FOR) Ecologists
conducted a review of the following aspects of the CCISS tool (outlined
below). We are currently engaging with additional subject matter experts to
provide a review, including silviculturists, forest health specialists,
and tree breeders.

#### 1. Tree Species Environmental Suitability Ratings

The initial environmental suitability ratings were assigned in 2017 by
A. Banner (Coast and North Area), T. Braumandl (Kootenay-Boundary and
Thompson-Okanagan), W. MacKenzie (Alberta), and D. Meidinger (USA). A
subsequent review of this output in 2018-2019 led to some clarification
of definitions and modifications of initial ratings, which were reviewed 
again by regional experts in 2021. In 2024/25, further discussions between 
CCISS team members and FOR Ecologists led to a review of and several 
modifications to suitability rating definitions. The objective of this latest 
review was to refine the suitability ratings using expert knowledge and other 
available information sources, to assist with filling in gaps, and to document 
known issues for further follow-up in the future. The resulting suitability 
ratings provide a strong scientific foundation and a consistent baseline for 
further refinement using quantitative methods. Using the updated documentation 
and rating process outlined above, the FOR Ecologists began reviewing species 
suitability ratings in their respective regions in February 2025. This review is 
complete for the Coast Area, Omenica, Cariboo, and Thompson-Okanagan Regions. 
See Rating of Tree Species Environmental Suitability Technical Report (2025), 
available from the BC Data Catalogue, for a full overview of the suitability process to date. 

#### 2. Tree Species Environmental Suitability Definitions

FOR Ecologists have provided feedback on the supporting documentation
and definitions of Tree Species Environmental Suitability ratings. An
in-person meeting with the FOR Ecology team to review CCISS model
results and the historical species suitability ratings took place in
November 2024. Per request of the Ecology team, the CCISS team developed
new documentation outlining definitions and a multi-step rating process
for species environmental suitability ratings, which we presented back
to the Ecology team in December 2024. The CCISS team incorporated two
rounds of revision to the Species Environmental Suitability ratings
documentation resulting in a final version as of February 2025.

See the "Methods - Suitability Ratings" tab for more information.

#### 3. CCISS Tool Results

FOR Ecologists are core subject matter experts for CCISS and we have
engaged this group to perform an initial review of CCISS tool results.
The Ecologist review will provide insight into the CCISS tool’s
ecological accuracy and alignment with current ecological knowledge,
help identify issues, and inform readiness for broader implementation.
An in-person meeting with the Provincial Ecology team to review CCISS
model results and the historical species suitability ratings took place
in November 2024. All Ecology team members have used and interacted with
the CCISS tool, documenting issues they identified with CCISS model
results via Github issues. In addition to feedback provided through
GitHub, we held individual meetings for each Forest Region to gather an
initial round feedback in March 2025. This review is ongoing and
iterative as we incorporate updates to the inputs (e.g., suitability
ratings) and models (e.g., BGC model).

#### 4. CCISS Tool Layout and Documentation

FOR Ecologists have also provided feedback on aspects of the layout of
the CCISS tool, information presentation, and supporting documentation.
