---
title: 
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
editor_options: 
  markdown: 
    wrap: 72
---

### BGC mapping as a baseline

CCISS results assess change in species suitability relative to the official biogeoclimatic mapping, rather than the baseline prediction of the biogeoclimatic model. This approach breaks a standard practice of climate impacts modeling: Change in a modeled quantity should be assessed against a modeled baseline. We have taken this approach to simplify interpretation of CCISS results. Our rationale is explained below. 

Biogeoclimatic models are trained on biogeoclimatic mapping (the response variable) and 1961-1990 climate normals (the predictor variables) for a sample of locations. When the model is then used to predict the biogeoclimatic unit from 1961-1990 climate normals, this is called a *baseline prediction*. Baseline predictions do not perfectly reproduce the original biogeoclimatic mapping because of imperfections in the biogeoclimatic model, biogeoclimatic mapping, and climate mapping. Biogeoclimatic models typically have baseline prediction error of ~20%, meaning that the baseline biogeoclimatic prediction is different than the official biogeoclimatic subzone/variant mapping on about 20% of the landscape. In many cases where these differences occur, the predicted unit is closely related to the mapped unit and there is negligible consequence for tree species suitability inferences. 

Baseline predictions are the technically correct point of comparison for biogeoclimatic projections of recent or future climates. If the mapped biogeoclimatic unit is used as a baseline, there is the potential to confuse model error with an actual change in climate. This conflation of model error with real changes causes overestimation of biogeoclimatic turn-over, but it can produce underestimation or overestimation of changes in species suitability. The impact of this conflation will be greatest in the recent period (2001-2020) since the magnitude of prediction error relative to climate change decreases over time. 

Even though a modeled baseline prediction is strictly more correct, we have chosen to use the official biogeoclimatic mapping as the baseline for CCISS results. The benefit of this approach is that the starting point for users will be the expected biogeoclimatic unit and species suitability ratings of their locations of interest. The alternative--using the modeled baseline prediction--would in some cases produce a baseline biogeoclimatic unit that is different than the biogeoclimatic unit of interest. This would not be tenable for core CCISS end uses such as silviculture prescriptions and stocking standards development. 

Given that the mapped and predicted baseline BGC unit are different on <20% of most landscapes, and that these differences are inconsequential for species suitability interpretations in many cases, the practical impact of this approach is likely not large. Nevertheless, we have not yet assessed this issue quantitatively. Users are encouraged to use the CCISS spatial module to assess baseline prediction errors for locations of critical interest and to consider the implications for species suitability interpretations. 

