---
title: 
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
editor_options: 
  markdown: 
    wrap: 72
---

### Integrating CCISS results into tree species selection

CCISS is intended as an input to tree species selection decisions, not a one-stop-shop. CCISS provides a  foundation of BEC-based interpretations that is comprehensive (all species for all site series across BC) but incomplete. Any tree species selection decision needs to account for other information, synthesized through professional judgement, including sources of error (discussed previously), other lines of evidence, and non-BEC factors. 

#### Other lines of evidence

The current CCISS analysis is a single modeling methodology with inherent assumptions and sources of error. Ideally, species selection decisions should be based on multiple lines of observational and modeling evidence. The CCISS team is collecting observational data and is planning to integrate CCISS analysis with other modeling approaches. In the interim, practitioners are encouraged to integrate the following information sources into their decisions:  

- Off-site species performance trials
- Forest Drought Assessment Tool
- Climate Based Seed Transfer 
- Professional experience

#### Non-BEC factors
CCISS adds a climate change dimension to the tree species interpretations of the BEC system. This approach accounts for many of the climatic and site factors in tree species selection. However, there are many non-BEC factors that are not directly accounted for in CCISS: 

- **Insects & disease**---the role of forest health factors is explicitly excluded from the CCISS environmental feasibility ratings, with the intention that they are a separate layer of information in reforestation decisions.  
- **Silvicultural systems**---species feasibility for reforestation is strongly affected by overstorey shade, site preparation, and microsite selection. In some cases, specialized silviculture practices will be required to establish trees on novel sites for which they are likely to be suitable in the future. Silviculture considerations are to some extent captured in CCISS implicitly or via footnotes. However, CCISS projections may in many cases be conservative because they do not account for the role of silviculture practices in compensating for climate and site constraints. 
- **Migration lag**---the historical range of tree species in British Columbia in many cases may be smaller than their potential range due migration lag following the end of the last glaciation. Since CCISS feasibility ratings are generally based on natural species ranges, migration lag is another reason why CCISS projections are likely to underestimate the assisted range expansion potential of some tree species. - **Extreme weather**---the current CCISS methodology assumes that changes in the mean climate are representative of changes in the extremes (the stationarity assumption). This is a reasonable starting point, and a necessary one since incorporating climate extremes into the CCISS analysis is non-trivial. However, climate change clearly violates the stationarity assumption: the 2021 Pacific Northwest heat dome vividly illustrates that the distribution of extremes is changing across all regions. The change in extremes relative to the mean is another dimension of novelty in the climates of the future, and thus another way in which spatial climate analogs can under-represent climate changes. The extent to which the changes in extremes is significant for CCISS projections is undetermined, but deserves careful consideration during species selection. 
