---
title: 
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
editor_options: 
  markdown: 
    wrap: 72
---

## Glossary of Terms: ###

**Assisted migration:**
<p style="margin-left: 2em;"> Assisted migration is the human-assisted relocation of species to new habitats, where they have not occurred in the past, to help them adapt to environmental change, including climate change. One of the goals of the CCISS tools is to help identify tree species that would make good candidates for assisted migration. </p>

**Biogeoclimatic Ecosystem Classification (BEC)**: 
<p style="margin-left: 2em;"> Biogeoclimatic Ecosystem Classification is a tool used to classify ecosystems in British Columbia according to vegetation, climate, and soils. It is often used in forestry and conservation in the province, and relies on the classification of ecosystems according to mature (climax) successional stages. For more information, see the <a href="https://www.for.gov.bc.ca/hre/becweb/" target="_blank">BEC website</a>.</p>

**Biogeoclimatic projections:**
<p style="margin-left: 2em;">Biogeoclimatic projections are modelled forecasts that predict how climate analogs of biogeoclimatic subzone/variants may shift over time in response to climate change. They involve using a statistical model to assign climate analogs of projected biogeoclimatic subzone/variants, and subsequently, which tree species will be suitable at a location over time.  </p>

**Biogeoclimatic subzone/variants (i.e., BGC units):**
<p style="margin-left: 2em;"> Biogeoclimatic subzone/variants are the biogeoclimatic map units of reference that the CCISS tool uses. In BEC 13, there are 211 BGC units. Each unit is classified by its biogeoclimatic zone (Definitions - BEC Codes - Table 1), and its subzone/variant (Definitions - BEC Codes - Table 2). Subzones are represented by the unit's relative precipitation and temperature, and variants are different clusters of subzones in the province, denoted with a number. For example, the ESSFdc1 BGC unit is part of the Engelmann Spruce - Subalpine Fir biogeoclimatic zone, and the *dc1* component designates it as the Okanagan Dry Cold subzone/variant. For a complete list of BGC subzone/variants, see the <a href="https://www.for.gov.bc.ca/hre/becweb/resources/classificationreports/subzones/index.html" target="_blank">BEC website</a>.</p>

**Chief Forester's Reference Guide (CFRG):**
<p style="margin-left: 2em;"> The <a href="https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/silviculture/stocking-standards/reference-guide/reference_guide_stocking_standards_20210907.xlsx" target="_blank">Chief Forester's Reference Guide for Stocking Standards</a> is the official guide to choosing suitable species and stocking levels for reforestation programs in British Columbia. </p>

**Classification model:**
<p style="margin-left: 2em;"> A classification model is a type of machine learning model (including that ensemble learning models such as Random Forest) that categorizes input data into predefined classes based on patterns in the data. In CCISS, it is used to classify future climate conditions into biogeoclimatic subzone/variant analogs based on climate variables. For more information, see *Random Forest model*. </p>

**Climate:**  
*Baseline climate:*  
<p style="margin-left: 2em;"> The historical climate used to compare observed climates of more recent periods or simulated future climates. The CCISS baseline period is 1961-1990. </p>
*Target climate:*  
<p style="margin-left: 2em;"> The current or future climate condition for which a historical analog is identified, and for which novelty is being measured. In CCISS, these are climatic averages over 20-year periods (2001-2020 through 2081-2100) for locations throughout BC. </p>
*Analog climate:*   
<p style="margin-left: 2em;"> The baseline climate condition assessed as being most similar to the target condition, among a set of candidate analogs. The analog pool for CCISS is the 1961-1990 climates of the biogeoclimatic subzone-variants of Western North America. </p>

**Climate analogs:** 
<p style="margin-left: 2em;"> Also known as biogeoclimatic (BGC) analogs, a climate analog is a location with a historical climate that is similar to the current or future projected climate of a different location. </p> 

**Climate projections:**
<p style="margin-left: 2em;"> Climate projections are model-based estimates of future climate conditions, including future precipitation and temperature in an area. These projections can be based on different greenhouse gas emissions scenarios. </p>

**Ecological suitability for a timber objective:** 
<p style="margin-left: 2em;"> This is a term used in the Chief Forester's Reference Guide. It refers to tree species that have been ranked and evaluated to optimize maximum sustainable productivity, crop reliability, and silvicultural feasibility. Species are designated as preferred or acceptable. **Preferred** species are ecologically suited to a site, and their establishment is a management priority. **Acceptable** species are also ecologically suited, but their establishment is not a management priority. Both conifer and broadleaf species are designated as preferred or acceptable. Only conifer species are also ranked as primary, secondary, or tertiary. **Primary** species are ecologically acceptable, and have high silvicultural feasibility, reliability, and productivity. **Secondary** species are also ecologically acceptable, but rank lower than primary species on feasibility, reliability, and productivity. Finally, **tertiary** species are also acceptable but rank lowest.</p>

<p style="margin-left: 2em;"> These definitions differ from the environmental suitability definitions used in the CCISS tool. For these, see Definitions - Suitability Definitions. For more information about Ecological suitability for a timber objective, see, for example, this report from the <a href="https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/silviculture/stocking-standards/efgg/efg-car-print.pdf" target="_blank">Cariboo Forest Region</a>.</p>

**Edatopic grid:**
<p style="margin-left: 2em;"> In the BEC system, variations in site conditions within each climate type (i.e., biogeoclimatic subzone/variant) are represented by an edatopic grid. An edatopic grid has 8 relative soil moisture regimes (SMRs) and 5 soil nutrient regimes (SNRs). Each cell in this grid, called an edatope, is the combination of one SMR and one SNR, and represents the finest scale of site differentiation in the BEC system. A site series is a group of edatopes over which a classified BEC Plant Association has been observed to occur. The distribution of site series across the edatopic grid is unique to each biogeoclimatic subzone/variant. </p>

**Ensemble:**
<p style="margin-left: 2em;">In the CCISS context, ensemble refers to a collection of independent climate model simulations used to capture a range of possible future climate outcomes and account for modeling uncertainty. CCISS quantifies three types of climate change uncertainty: modeling uncertainty, natural variability, and socioeconomic uncertainty. Rather than producing a single species suitability value, CCISS provides an 'ensemble' - i.e., a distribution of 60 suitability values (8 climate models x 1-3 simulation runs x 3 socioeconomic scenarios) for each future time-period. </p>

**Environmental suitability:**
<p style="margin-left: 2em;"> In CCISS, environmental suitability represents a response curve of species' tolerances to environmental (climatic and edaphic) gradients. CCISS incorporates historical (1961-1990) tree species suitability ratings for all site series in British Columbia as determined by expert knowledge. For more information, see Methods - Suitability Ratings. </p>

**Establishment suitability:**
<p style="margin-left: 2em;"> The suitability rating based on the mean historic, current (2001-2020), and 2021-2040 future projected suitabilities. This indicates the likely level of constraints for successful establishment of the species now.</p>

**Forecast:**   
<p style="margin-left: 2em;">“Projection”, “prediction”, and “forecast” are related terms with varying usage in ecology and climate science. See also "projection" and "prediction" in this glossary for a better understanding of all three terms. </p>

<p style="margin-left: 2em;">A forecast is an estimate of possible future states of a variable of interest. A forecast is not a “crystal ball” of what will happen, but a quantification of uncertainty in what could happen. Providing forecasts of environmental suitability for tree species is the ultimate goal of CCISS. CCISS forecasts are a synthesis of many projections of tree species suitability that have been carefully selected to provide a meaningful representation of uncertainty.</p> 

**Fundamental niche:**
<p style="margin-left: 2em;"> A fundamental niche represents the full potential range of conditions a species could occupy, in theory, without limitations imposed by biotic interactions, such as competition. Compare with *realized niche* below. </p>

**Global climate models (GCMs)**: 
<p style="margin-left: 2em;"> "Global climate model" is a generic term that encompasses both Earth System Models and General Circulation Models. General Circulation Models model the physics of the ocean, atmosphere, land surface, and typically also the ice caps/sheets. Earth System Models additionally also model biogeoclimatic cycles (e.g., carbon cycle mechanisms such as vegetation growth, forest fires, etc).  </p>

**Historic suitability:**
<p style="margin-left: 2em;">The baseline environmental suitability rating based primarily on the expert suitability ratings of the historic period (19961-1990).</p>

**Maturation suitability:**
<p style="margin-left: 2em;">The mean suitability rating projected across the four 20-year normal periods (2021-2100). This indicates the inferred suitability of successfully growing an established species to maturity (80 years). </p>

**Novel climate/novelty:**
<p style="margin-left: 2em;"> A novel climate occurs when the projected future climate conditions in an area differ significantly from any historical climate analog available in western North America, making it difficult to find a reliable comparison. In the CCISS framework, climatic novelty is quantified using sigma dissimilarity, which compares future climates to the combined spatial and temporal variation of historical climate analogs.</p>

**Off-site:** See Out Home Range (OHR). 
<p style="margin-left: 2em;"> </p>

**Out Home Range (OHR) Suitability:** 
<p style="margin-left: 2em;"> The term “outside home range” refers to tree species environmental suitability ratings that have been assigned in a geographical area (i.e. biogeoclimatic subzone-variant) where the species does not occur naturally. In some cases, OHR species were restricted by something other than climate, such as migration limitations (for example, western larch) or forest health factors (for example, Western white pine limited by blister rust). In CCISS, we have included an environmental suitability rating for OHR species with strong evidence of being well adapted to the climatic conditions of the historical reference period (1961–1990), which serves as the basis for these ratings. </p>

**Prediction:**   
<p style="margin-left: 2em;"> “Projection”, “prediction”, and “forecast” are related terms with varying usage in ecology and climate science. See also "projection" and "forecast" in this glossary for a better understanding of all three terms. </p>


<p style="margin-left: 2em;"> In CCISS, the term prediction is used exclusively as *model prediction*: the process by which a statistical model estimates a response variable (i.e., biogeoclimatic subzone/variant analog) based on predictor variables (i.e., climate variables). A model prediction can be made for any values of the predictor variables regardless of whether they represent past, future, or hypothetical conditions. Each biogeoclimatic projection for one 20-year time period is a model prediction. </p>


**Projection:**   
<p style="margin-left: 2em;"> “Projection”, “prediction”, and “forecast” are related terms with varying usage in ecology and climate science. See also "forecast" and "prediction" in this glossary for a better understanding of all three terms. </p>

<p style="margin-left: 2em;"> A projection is an estimate of the change over time in a variable of interest given a specific set of assumptions. CCISS provides one projection of tree species suitability for each of three simulations of eight global climate models following three atmospheric greenhouse gas concentration scenarios. The 2001-2020 period of these simulations is considered a projection even though it occurs in the past. </p>

**Random Forest model:**
<p style="margin-left: 2em;"> A Random Forest model is an ensemble learning method that constructs multiple decision trees during training, and combines their outputs to improve predictive accuracy and to prevent overfitting. It works by randomly selecting subsets of data and features (variables) for each tree. In the case of classification models, including the ones used in CCISS, it then uses majority voting to classify projected biogeoclimatic subzone/variants (i.e., the most frequently chosen BGC subzone/variant is the final classification). </p>

**Realized niche:**
<p style="margin-left: 2em;"> A realized niche is the actual environmental conditions and resources that a species occupies and uses, considering competition, predation, and other biotic interactions. This makes it narrower than a *fundamental niche* (see above). </p>

**Shared Socioeconomic Pathways (SSPs):**
<p style="margin-left: 2em;">Shared Socioeconomic Pathways (SSPs) are future global development scenarios that describe different ways that society, economics, and policies might evolve regarding greenhouse gas emissions and their impacts on climate change. CCISS includes projections for three SSP scenarios: SSP1-2.6, SSP2-4.5, and SSP3-7.0, representing optimistic, moderate, and high-emission futures. SSP1-2.6 aligns with strong mitigation efforts to limit warming to 2°C, SSP2-4.5 reflects current policies with moderate mitigation, and SSP3-7.0 assumes no mitigation, leading to steadily increasing emissions.</p>

**Site series:**
<p style="margin-left: 2em;"> A site series is a group of edatopes (i.e., unique combinations of soil moisture regimes and soil nutrient regimes) over which a classified BEC Plant Association has been observed to occur. The distribution of site series across the edatopic grid is unique to each biogeoclimatic subzone/variant. See also *edatopic grid*.</p>

**Stocking standards:**
<p style="margin-left: 2em;"> Stocking standards are regulations or guidelines that define the distribution and composition of trees that must be established after harvesting to ensure successful forest regeneration. Specifically, these standards designate densities, acceptable species, and spacing requirements. </p>

**Suitability projections:**
<p style="margin-left: 2em;"> Suitability projections refer to the future tree species suitability ratings forecasted by the CCISS tool (see Methods - Suitability Ratings). </p>

**Uncertainty:**
<p style="margin-left: 2em;">In reference to CCISS, uncertainty refers to the range of potential variability in model predictions, and comes from various sources. CCISS quantifies three types of climate change uncertainty: modeling uncertainty, natural variability, and socioeconomic uncertainty. These uncertainties are represented by calculating CCISS results for a large ensemble of potential future climate states. For more information, see Methods - Climate Change Projections.  </p>
