---
title: 
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
editor_options: 
  markdown: 
    wrap: 72
---

### Frequently Asked Questions

#### If the climate model ensemble mean is different than the historical climate, does this mean the climate models are wrong?

The historical climate is one observation of many possible climate
states that could have occurred due to the internal variability
(weather) of the Earth’s climate system. Differences between the
ensemble mean projection and the observed climate are not necessarily a
contradiction; like climate vs. weather, the ensemble mean is the
expectation and the observed climate is what actually happened.

However, if the observed climate is completely outside the range of the
individual model runs, this is a problem. There are two major reasons
why this could occur: (1) the downscaled model ensemble is failing to
capture some aspect of regional climate dynamics; or (2) the
observations themselves are biased due to errors in the station
observations or in the gridded interpolation between stations. Both of
these potential sources of error are an active area of research by the
CCISS team.

#### Does the CCISS tool account for forest health factors?

No. The role of forest health factors is explicitly excluded from the
CCISS environmental suitability ratings, with the intention that they
are a separate layer of information in reforestation decisions. CCISS is
one modeling methodology that considers climate change implications for
tree species suitability. Ultimately decisions on species selection
should be made using multiple lines of evidence, including insects and
disease.

#### Why does the CCISS model promote or demote certain species?

The species projected suitability ratings are based on environmental
suitability assigned to site series within each BGC subzone-variant. The
CCISS model selects BGCs that match the future climate projections for
the point(s) or BGC of interest. Future species suitability projections
are then pulled from the BGCs projected for that point or area. Go to
the “BEC futures” tab to see the breakdown of which BGCs are projected.

#### What are the climate drivers of species suitability trends?

This functionality does not currently exist in the CCISS tool. We are
planning to include a climate component in CCISS spatial in the future.

#### What do C4, B2 and D6 refer to in the CCISS Spatial Module? And why does SNR come first?

These are soil nutrient regime (SNR)/ soil moisture regime (SMR)
edatopes, indicating poor/subxeric (B2), mesic/medium (C4) and
rich/hygric (D6) site types across all BGCs. Providing spatial data for
all 35 edatopes would be too computationally feasible, so we chose these
three edatopes to represent distinct, common site types. Although it is
typical to place SMR first in edatope names (e.g., 4C), we put SNR first
because it is much more convenient in computer code.

#### What is the uncertainty around the current suitability ratings for the modeled US BEC units?

There is no equivalent, published biogeoclimatic ecosystem
classification and mapping for forest ecosystems of the United States.
In the CCISS tool, we use a draft classification of biogeoclimatic units
for Washington, Idaho, Montana, Oregon, northern California, and
northwestern Wyoming to provide potential future climate analogues for
British Columbia (details in MacKenzie & Meidinger 2024 - [BC Data
Catalogue](https://catalogue.data.gov.bc.ca/dataset/cciss-western-north-america-bec-tables)).
Site series classifications were developed, and species suitability
ratings were assigned by an expert ecologist based on available plot
data from the US and site visits.

There is a higher level of uncertainty associated with the US
biogeoclimatic classification as the draft site series classification
for US BGC units is more generic and broader (i.e. larger edatopic
range) than BC, consequently there is less specificity on tree species
suitability. Additionally, biogeoclimatic units are at the subzone
level, and in some cases are climatically more diverse than BC units
which are at the subzone-variant level. Finally, the species ratings
have received less expert review and quantitative validation than those
in BC, although they are expert derived and site visits have occurred.

Despite these limitations, the inclusion of these draft US BGC units and
associated environmental suitability ratings result in much reduced
uncertainty in CCISS projections compared to their absence, as the
analogs for future climate in much of southern BC are located across the
border in the US. .

#### Why doesn’t the US BEC match up with BC BEC across the border?

We are currently integrating the updated BEC classification and mapping
for BEC13 (coast region – LMH77). With BEC13, we are also updating
mapping of US BEC and are working to align biogeoclimatic mapping across
the US – Canada border.

#### What is the difference between a projection and a prediction?

“Projection”, “prediction”, and “forecast” are related terms with
varying usage in ecology and climate science. For the purposes of CCISS
we use the following definitions:

-   **Forecast**—A forecast is an estimate of possible future states of
    a variable of interest. A forecast is not a “crystal ball” of what
    will happen, but a quantification of uncertainty in what could
    happen. Providing forecasts of environmental suitability for tree
    species is the ultimate goal of CCISS. CCISS forecasts are a
    synthesis of many estimates of tree species suitability that have
    been carefully selected to provide a meaningful representation of
    uncertainty.

-   **Projection**—A projection is an estimate of the change over time
    in a variable of interest given a specific set of assumptions. CCISS
    provides one projection of tree species suitability for each of
    three simulations of eight global climate models following three
    atmospheric greenhouse gas concentration scenarios. The 2001-2020
    period of these simulations is considered a projection even though
    it occurs in the past.

-   **Prediction**—In CCISS, the term prediction is used exclusively as
    model prediction: the process by which a statistical model estimates
    a response variable (i.e., biogeoclimatic subzone/variant analog)
    based on predictor variables (i.e., climate variables). A model
    prediction can be made for any values of the predictor variables
    regardless of whether they represent past, future, or hypothetical
    conditions. Each biogeoclimatic projection for one 20-year time
    period is a model prediction.

#### In the CCISS spatial popup charts, why do the proportions of suitabilities not match the proportions of BGC analogs?

If there was always only one site series for each edatope, then the
proportions in the BGC and suitability plots would match. However, some
site series overlap on the edatopic grid or share an edatope. In these
cases, there will be two suitabilities for each BGC analog. As a result,
the BGC and suitability proportions are not necessarily the same. See
Documentation \> Methods \> Edatopic Overlap.

#### In the CCISS spatial popup charts, why do the proportions of suitabilities not match the proportions of BGC analogs?

If there was always only one site series for each edatope, then the
proportions in the BGC and suitability plots would match. However, some
site series overlap on the edatopic grid or share an edatope. In these
cases, there will be two suitabilities for each BGC analog. As a result,
the BGC and suitability proportions are not necessarily the same. See
Documentation \> Methods \> Edatopic Overlap.

#### What does "decrease of 1" in environmental suitability mean in practical terms? How we should I interpret this in situations like ops planning?

A decrease of 1 means that suitability is expected to decline. For
operational purposes, the actual change in rating is important. For
example where a species is historically rated an E1 and drops to an E2 -
this represents a species that was well within its environmental
tolerance (high environmental suitability), which is projected to become
moderately suitable - i.e. is outside of its core environmental
tolerance range, may be more susceptible to climatic extremes and may
have lower growth and survival, but is still suitable and could remain a
good choice for planting depending on the specific values/goals for that
stand. That would be quite different from a species that was an E3 - low
environmental suitability - dropping to "unsuitable", this would
represent a species that was at the edge of its environmental
suitability, will likely become unsuitable in the future, and would not
be a good choice for planting.

It is important to emphasize that CCISS is a "tool" and should be used
alongside local knowledge and within the context of desired values/goals
to make reforestation decisions. So a decrease of 1, while at a broad
scale means suitability is declining, could lead to different management
decisions in practice.

#### Are the tree species environmental suitability ratings consistent across all species?

Ratings are applied consistently across species (See “Methods” –
“Suitability Ratings”). While they are not perfect, they are expert
derived and have gone through an expert review process to achieve a
strong scientific foundation (See “Methods” – “Expert Review”).
Quantitative validation of the environmental suitability ratings is
currently underway (See “Resources”- “CCISS Technical Reports” -
“[Ratings of Tree Species Environmental
Suitability](https://catalogue.data.gov.bc.ca/dataset/cciss-environmental-suitability-ratings-)”).
Note that environmental suitability does not include forest health
factors so those may vary from species to species even where the
suitability rating is equivalent.

#### Do the environmental suitability ratings represent a linear scale?

Species environmental suitability is not rated on a strictly linear
scale. See “Methods” – “Suitability Ratings” for the ratings
definitions. Furthermore, increases or decreases in environmental
suitability ratings do not necessarily scale linearly with changes in
relative abundance for a species, but these metrics are generally
positively correlated. Depending on the application it can be useful to
look at trends in suitability change. For example, in CCISS Spatial we
use the relative change in species suitability to demonstrate broad
scale trends in a species across the province. See the CCISS Spatial tab
on CCISS and choose "Suitability" - "Future (GCMs)" - "Suitability
Change".

In a case study on Douglas-fir, species environmental suitability
ratings showed a positive relationship with relative abundance of the
species in the BEC plot dataset. In other words, site series with higher
environmental suitability ratings also had higher relative % cover of
Douglas-fir. However, the strength of this positive relationship varied
by biogeoclimatic zones, with higher agreement in zones where
Doughlas-fir is a dominant species at the regional scale, (e.g. Interior
Douglas-fir (IDF), Coastal Douglas-fir (CDF) zones) and less agreement
in zones with more mixed species composition (e.g. Interior Coastal
Hemlock (ICH), and Sub Boreal Spruce (SBS) zones). For more details see
“Documents”- “CCISS Technical Reports” - “[Ratings of Tree Species
Environmental
Suitability](https://catalogue.data.gov.bc.ca/dataset/cciss-environmental-suitability-ratings-)”).
