---
title: 
output: 
    html_document:
        theme: null
        highlight: null
        mathjax: null
---

### Feasibility (Environmental Suitability) Ratings

The [Establishment to Free Growing Guidebooks](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/silviculture/stocking-standards) and [Chief Forester's Reference Guide for Stocking Standards](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/silviculture/stocking-standards/reference-guide/reference_guide_stocking_standards_20210907.xlsx) (CFRG) rank ecologically acceptable species for each site series. Three criteria are used to determine the most suitable species choices for sawlog production (the assumed management goal) based on an assessment of:

-   maximum sustainable productivity
-   crop reliability
-   silvicultural feasibility.

The rankings applied always have at least one "primary" species for each site series indicating the best species choice to meet the timber objective.

In contrast, the CCISS tool assesses the environmental suitability rating to species, which focuses on how well the species is suited to the climatic and site conditions of a site series regardless of management objective. Each tree species has adapted to a specific range of environmental conditions, and its growth and behaviour depend on the ecosystem in which it grows. In an unfavourable environment, that species growth potential will not be realized, and its susceptibility to damaging agents will increase. Unlike the ratings applied in the CFRG, site series with generally challenging growing conditions may have no tree species assigned to the highest suitability rating.

Insect and disease risks need to be considered in reforestation, particularly in the context of climate change. These factors are currently being assessed by Forest Health researchers.

Feasibility (environmental suitability) ratings are defined as follows:

**E1 -- High environmental suitability**: Typically, no environmental limiting conditions for establishment and growth across the full range of site series conditions.

**E2 -- Moderate environmental suitability**: Once tree species are successfully established, they will generally perform well. However;

-   species may be more susceptible to occasional but expected climatic extremes leading to mortality, damage, or reduced growth (e.g. drought periods);

-   some site types of the site series conditions may have higher constraints for the species leading to poor regeneration success or subsequent growth (e.g. frost prone locations or overly wet sites in Sx -- Horsetail site series),

-   may express slow growth rates across all conditions (e.g. woodland subzones or Xeric sites with \~SI50 \< 8m)

**E3 -- Low environmental suitability**: Establishment and growth may be limited to specific site conditions of the site series but may perform well where successfully established.

-   expected climatic extremes have a high probability of causing reduced growth, damage or mortality in some years (e.g. drought periods);

-   a limited set of site series conditions are considered feasible for the species though it may perform well under these constraints (e.g. only feasible on warm aspect, lower elevations of the ESSF);

-   species may express very low growth rates across all conditions (e.g. parkland subzones or rock outcrops with SI50 \< 5m)

**Non-local Feasibility**: Off-site trials indicate that a non-local species was feasible in the pre-climate change period but that migration lag or some other barrier restricted establishment.

**Trial**: Species is not recognized as historically feasible for a site series but is projected to become feasible in the near future. Establishment of small operational trials recommended to provide information on possible inclusion of species in feasible species list.

**Unsuitable**: Unlisted species are considered to be unsuitable to the site series in current and future periods. Future projections may indicate species are becoming unsuitable. This indicates that the climatic regime may impose serious growth constraints on the established species but may not necessarily indicate mortality.

Feasibility for different time periods, given the progression of climate change, are given the following terms in the CCISS tool:

**Historic Feasibility**: The baseline environmental suitability rating based primarily on the CFRG and the historic period pre 1991.

**Establishment Feasibility**: The feasibility rating based on the mean historic, current, and 2021-2040 future projected feasibilities. This indicates the likely level of constraints for successful establishment of the species now.

**Maturation Feasibility**: The mean feasibility rating based on the 4 future modelled 2021-2040 future projected feasibilities. This indicates the likely level of constraints for successful establishment of the species now.
