# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gs2gw <- function(x, a, b) {
    .Call(`_ccissdev_gs2gw`, x, a, b)
}

SimGrowth <- function(DF, ProbPest, cmdMin, cmdMax, tempMin, tempMax, climLoss) {
    .Call(`_ccissdev_SimGrowth`, DF, ProbPest, cmdMin, cmdMax, tempMin, tempMax, climLoss)
}

combCurr <- function(dat, wt) {
    .Call(`_ccissdev_combCurr`, dat, wt)
}

NewSuitNoCurr <- function(x, vals) {
    .Call(`_ccissdev_NewSuitNoCurr`, x, vals)
}

FeasSuit <- function(x, Curr, vals, CurrAdj) {
    .Call(`_ccissdev_FeasSuit`, x, Curr, vals, CurrAdj)
}

stepDiff <- function(Year, NewSuit, Curr) {
    .Call(`_ccissdev_stepDiff`, Year, NewSuit, Curr)
}

ModelDir <- function(x, Curr, dir) {
    .Call(`_ccissdev_ModelDir`, x, Curr, dir)
}

