# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combCurr <- function(dat, wt) {
    .Call(`_CCISS_combCurr`, dat, wt)
}

NewSuitNoCurr <- function(x, vals) {
    .Call(`_CCISS_NewSuitNoCurr`, x, vals)
}

FeasSuit <- function(x, Curr, vals, CurrAdj) {
    .Call(`_CCISS_FeasSuit`, x, Curr, vals, CurrAdj)
}

stepDiff <- function(Year, NewSuit, Curr) {
    .Call(`_CCISS_stepDiff`, Year, NewSuit, Curr)
}

ModelDir <- function(x, Curr, dir) {
    .Call(`_CCISS_ModelDir`, x, Curr, dir)
}

bifurcTrend <- function(Imp, Decl) {
    .Call(`_CCISS_bifurcTrend`, Imp, Decl)
}

